<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

use DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    { 
        // ---------------K100 products---------------
        
        DB::table('products')->insert([
            'product_name' => 'K100 Normal Profile Keyboard Hot Swap',
            'product_type' => 'K100',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '100%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 400.00,

            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',

        ]);

        DB::table('products')->insert([
            'product_name' => 'K100 Low Profile Keyboard Hot Swap',
            'product_type' => 'K100',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '100%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 400.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
            
        ]);

        DB::table('products')->insert([
            'product_name' => 'K100 Ultra-Low Profile Keyboard Hot Swap',
            'product_type' => 'K100',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '100%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 400.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K100 Normal Profile Wireless Keyboard Hot Swap',
            'product_type' => 'K100',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '100%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 450.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K100 Low Profile Wireless Keyboard Hot Swap',
            'product_type' => 'K100',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '100%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 450.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K100 Ultra-Low Profile Wireless Keyboard',
            'product_type' => 'K100',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '100%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 450.00,
            
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K100 Normal Profile Keyboard',
            'product_type' => 'K100',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '100%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 350.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K100 Low Profile Keyboard',
            'product_type' => 'K100',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '100%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 350.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        // ---------------K100 products end---------------


        // ---------------K96 products---------------

        DB::table('products')->insert([
            'product_name' => 'K96 Normal Profile Keyboard Hot Swap',
            'product_type' => 'K96',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '96%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 350.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K96 Low Profile Keyboard Hot Swap',
            'product_type' => 'K96',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '96%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 350.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K96 Ultra-Low Profile Keyboard Hot Swap',
            'product_type' => 'K96',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '96%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 350.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K96 Normal Profile Wireless Keyboard Hot Swap',
            'product_type' => 'K96',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '96%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 400.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K96 Low Profile Wireless Keyboard Hot Swap',
            'product_type' => 'K96',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '96%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 400.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K96 Ultra-Low Profile Wireless Keyboard',
            'product_type' => 'K96',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '96%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 400.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K96 Normal Profile Keyboard',
            'product_type' => 'K96',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '96%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 300.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K96 Low Profile Keyboard',
            'product_type' => 'K96',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '96%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 300.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        // ---------------k96 products end---------------



        // ---------------K80 products---------------

        DB::table('products')->insert([
            'product_name' => 'K80 Normal Profile Keyboard Hot Swap',
            'product_type' => 'K80',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '80%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 300.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K80 Low Profile Keyboard Hot Swap',
            'product_type' => 'K80',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '80%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 300.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K80 Ultra-Low Profile Keyboard Hot Swap',
            'product_type' => 'K80',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '80%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 300.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K80 Normal Profile Wireless Keyboard Hot Swap',
            'product_type' => 'K80',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '80%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 350.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K80 Low Profile Wireless Keyboard Hot Swap',
            'product_type' => 'K80',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '80%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 350.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K80 Ultra-Low Profile Wireless Keyboard',
            'product_type' => 'K80',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '80%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 350.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K80 Normal Profile Keyboard',
            'product_type' => 'K80',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '80%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 250.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'K80 Low Profile Keyboard',
            'product_type' => 'K80',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '80%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 250.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        // ---------------k80 products end---------------

        // ---------------k75 products---------------

        DB::table('products')->insert([
            'product_name' => 'k75 Normal Profile Keyboard Hot Swap',
            'product_type' => 'k75',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '75%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 250.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k75 Low Profile Keyboard Hot Swap',
            'product_type' => 'k75',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '75%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 250.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k75 Ultra-Low Profile Keyboard Hot Swap',
            'product_type' => 'k75',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '75%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 250.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k75 Normal Profile Wireless Keyboard Hot Swap',
            'product_type' => 'k75',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '75%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 350.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k75 Low Profile Wireless Keyboard Hot Swap',
            'product_type' => 'k75',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '75%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 350.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testtestImageTumbnailImage.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k75 Ultra-Low Profile Wireless Keyboard',
            'product_type' => 'k75',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '75%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 350.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k75 Normal Profile Keyboard',
            'product_type' => 'k75',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '75%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 200.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k75 Low Profile Keyboard',
            'product_type' => 'k75',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '75%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 200.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        // ---------------k75 products end---------------


        // ---------------k60 products---------------

        DB::table('products')->insert([
            'product_name' => 'k60 Normal Profile Keyboard Hot Swap',
            'product_type' => 'k60',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '60%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 200.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k60 Low Profile Keyboard Hot Swap',
            'product_type' => 'k60',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '60%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 200.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k60 Ultra-Low Profile Keyboard Hot Swap',
            'product_type' => 'k60',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '60%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 200.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k60 Normal Profile Wireless Keyboard Hot Swap',
            'product_type' => 'k60',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '60%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 300.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k60 Low Profile Wireless Keyboard Hot Swap',
            'product_type' => 'k60',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '60%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 300.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k60 Ultra-Low Profile Wireless Keyboard',
            'product_type' => 'k60',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '60%',
            'connectivity' => 'wireless',
            'stock' => '50',
            'price' => 300.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k60 Normal Profile Keyboard',
            'product_type' => 'k60',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '60%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 150.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        DB::table('products')->insert([
            'product_name' => 'k60 Low Profile Keyboard',
            'product_type' => 'k60',
            'description' => 'Engineered to maximize your productivity with most popular full size layout with number pad. The hot-swappable option on Gateron switches and Keychron switches offers the freedom to easily personalize your typing experience without soldering.',
            'size' => '60%',
            'connectivity' => 'wired',
            'stock' => '50',
            'price' => 150.00,
            'main_image' => 'testImage.jpg',
            'tumbnail_main_image' => 'testImageTumbnail.jpg',
            'large_main_image' => 'testImageLarge.jpg',

            'sub_image_1' => 'testImage.jpg',
            'tumbnail_sub_image_1' => 'testImageTumbnail.jpg',
            'large_sub_image_1' => 'testImageLarge.jpg',
            'display_1' => 'block',
            'tumbnail_display_1' => 'block',
            'large_display_1' => 'block',

            'sub_image_2' => 'testImage.jpg',
            'tumbnail_sub_image_2' => 'testImageTumbnail.jpg',
            'large_sub_image_2' => 'testImageLarge.jpg',
            'display_2' => 'block',
            'tumbnail_display_2' => 'block',
            'large_display_2' => 'block',

            'sub_image_3' => 'testImage.jpg',
            'tumbnail_sub_image_3' => 'testImageTumbnail.jpg',
            'large_sub_image_3' => 'testImageLarge.jpg',
            'display_3' => 'block',
            'tumbnail_display_3' => 'block',
            'large_display_3' => 'block',

            'sub_image_4' => 'testImage.jpg',
            'tumbnail_sub_image_4' => 'testImageTumbnail.jpg',
            'large_sub_image_4' => 'testImageLarge.jpg',
            'display_4' => 'block',
            'tumbnail_display_4' => 'block',
            'large_display_4' => 'block',

            'sub_image_5' => 'testImage.jpg',
            'tumbnail_sub_image_5' => 'testImageTumbnail.jpg',
            'large_sub_image_5' => 'testImageLarge.jpg',
            'display_5' => 'block',
            'tumbnail_display_5' => 'block',
            'large_display_5' => 'block',
        ]);

        // ---------------k60 products end---------------
        

    }
}